module api {
    typedef octet byteArray[4*1024];
    interface DataNode {
        byteArray read(in long block_id);
        void append(in long block_id, in byteArray bytes);
        long randomBlockId();
    };
    interface NameNode{
    //TODO: complete the interface design
            // 打开文件的方法
            string open(in string filepath, in long mode);
            // 关闭文件的方法
            void close(in string fileInfo);
    };
};
